language: python

matrix:
  include:

    # Here you can add or remove specific builds, and Python versions. You
    # should currently be able to use Python 2.6, 2.7, or 3.3 or later. The
    # NUMPY and SCIPY versions are set here as an example, but you can
    # add/remove environment variables, and use them below during the install.

    - python: 2.7
      env: NUMPY=1.14 

    - python: 3.5
      env: NUMPY=1.15 
os:
  - linux

sudo: false

install:
  # Install Anaconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION 
  - source activate test-environment
  - conda install --yes numpy=$NUMPY pytest conda-build
  - conda install -c conda-forge sparse
  - conda build src/Python/conda-recipe --numpy=$NUMPY --python=$TRAVIS_PYTHON_VERSION 
  - conda install --channel /home/travis/miniconda/envs/test-environment/conda-bld/ tomobar --offline --override-channels

after_success:
  - source activate test-environment
  - conda config --set anaconda_upload yes
  - conda build src/Python/conda-recipe --numpy=$NUMPY --python=$TRAVIS_PYTHON_VERSION
  
script:
  - python tests/test.py

