package:
  name: tomobar
  version: {{ environ['VERSION'] }}
  
build:
  preserve_egg_dir: False
  number: 0
  script_env:
    - VERSION

requirements:
  build:
    - python
    - numpy
    - setuptools
    - cython
    - cmake

  run:
    - python
    - numpy
    - libgcc-ng # [unix]

about:
  home: https://github.com/dkazanc/ToMoBAR
  license:  GPLv3
  summary: 'TOmographic MOdel-BAsed Reconstruction (ToMoBAR) software'
