package:
  name: tomobar
  version: {{ environ['VERSION'] }}

build:
  preserve_egg_dir: False
  number: 0
  script_env:
    - VERSION

test:
  source_files:
    - ./test/
  commands:
    - python -c "import os; print (os.getcwd())"
    - python -m unittest discover -s test

requirements:
  build:
    - python
    - numpy
    - setuptools
    - cython
    - cmake
  run:
    - scipy
    - python
    - numpy
    - libgcc-ng # [unix]

about:
  home: https://github.com/dkazanc/ToMoBAR
  license:  GPLv3
  summary: 'TOmographic MOdel-BAsed Reconstruction (ToMoBAR) software'
