package:
  name: tomorec
  version: "0.1.1"


build:
  preserve_egg_dir: False
  
requirements:
  build:
    - python
    - numpy
    - setuptools
    
  run:
    - python
    - numpy
	
about:
  home: https://github.com/dkazanc/TomoRec
  license:  GPLv3
  summary: 'MATLAB/Python library of tomographic reconstruction methods: direct and iterative'
