package:
  name: tomobar
  version: "0.1.3"


build:
  preserve_egg_dir: False

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy

about:
  home: https://github.com/dkazanc/ToMoBAR
  license:  GPLv3
  summary: 'TOmographic MOdel-BAsed Reconstruction (ToMoBAR) software'
